# PostgreSQL database configuration

connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: finals
  password: password
  timeout: 5000

development:
  <<: *connection
  database: readr_database

test:
  <<: *connection
  database: rails_test
