# PostgreSQL database configuration

connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  timeout: 5000

development:
  <<: *connection

test:
  <<: *connection
  database: <%= "#{ENV['DB_DATABASE']}_test" %>

production:
  <<: *connection
